spring:
  profiles:
    active: dev
  datasource: # 数据库信息配置
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${hsa.datasource.host}:3306/${hsa.datasource.database}
    username: ${hsa.datasource.username}
    password: ${hsa.datasource.password}
    type: com.alibaba.druid.pool.DruidDataSource  # 设置druid数据源
  main:
    banner-mode: off  # 关闭spring的banner
server:
  port: 9003  # 端口号

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl   # 开启mp的日志 (输出到控制台)
    map-underscore-to-camel-case: true  # 开启驼峰命名
  global-config:  # 关闭mybatis的banner
    banner: false
  mapper-locations: classpath:/mapper/*.xml  # mapper文件位置
  type-aliases-package: com.hsasys.domain.entity # 实体类位置

baidu:
  ocr:
    appId: ${hsa.ocr.appId}
    apiKey: ${hsa.ocr.apiKey}
    secretKey: ${hsa.ocr.secretKey}

hsa:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    user-secret-key: poolexiaozhoudominoforHS256algorithm
    # 设置jwt过期时间
    user-ttl: 259200000
    # 设置前端传递过来的令牌名称
    user-token-name: Authorization
swagger:
  enable: true
#文件上传
dromara:
  x-file-storage: #文件存储配置
    default-platform: aliyun-oss-1 #默认使用的存储平台
    thumbnail-suffix: ".min.jpg" #缩略图后缀，例如【.min.jpg】【.png】
    #对应平台的配置写在这里，注意缩进要对齐
    aliyun-oss:
      - platform: aliyun-oss-1 # 存储平台标识
        enable-storage: true  # 启用存储
        access-key: ${hsa.alioss.access-key}
        secret-key: ${hsa.alioss.secret-key}
        end-point: ${hsa.alioss.endpoint}
        bucket-name: ${hsa.alioss.bucket-name}
        domain: ${hsa.alioss.domain} # 访问域名，注意“/”结尾，例如：https://abc.oss-cn-shanghai.aliyuncs.com/
        base-path: hsa/ # 基础路径